### ISSUE TITLE
Vehicle poller: PollSingleRequest speed & VWTP protocol regressions

### ISSUE THREAD

**Issue by dexterbg** [openvehicles/Open-Vehicle-Monitoring-System-3#1232]
Since PR #1010, multiple single poll requests in series are limited to one request per second, making Javascript toolkits like the UpMiiGo ECU plugin unusably slow or causing crashes.

Since PR #1012, the VWTP protocol is broken.

Examples + Logs, all with the same ECU scans (querying HW & SW info, Coding, Subroutines, DTCs etc.):

a) Pre-bug normal/expected behaviour; HEAD at bd4e7196 Merge pull request #1008 from frogonwheels/poller-task-fix:
- Scanning the ISOTP ECU  takes ~1 second, with complete & correct results
- Scanning the VWTP ECU takes ~5 seconds, with complete & correct results
[pollerbug-251101-scanlog-a.txt](https://github.com/user-attachments/files/23282937/pollerbug-251101-scanlog-a.txt)

b) Slowdown of all single polls; HEAD at b125dfef Merge pull request #1010 from frogonwheels/fix-obey-throttle:
- Scanning the ISOTP ECU takes ~20 seconds, still complete & correct results
- Scanning the VWTP ECU takes ~35 seconds, still complete & correct results
[pollerbug-251101-scanlog-b.txt](https://github.com/user-attachments/files/23282938/pollerbug-251101-scanlog-b.txt)

c) Partial ISOTP failure + complete VWTP failure; HEAD at 53713d9e Merge pull request #1012 from frogonwheels/fix-shutdown
- Scanning the ISOTP ECU takes ~20 seconds, incomplete results (some queries failed)
- Scannning tht VWTP ECU fails within 1 second with `ERROR: Login failed: Timeout waiting for poller/response`
[pollerbug-251101-scanlog-c.txt](https://github.com/user-attachments/files/23282936/pollerbug-251101-scanlog-c.txt)

Meanwhile (current master HEAD) ISOTP again delivers complete results, but still takes more than 20 seconds, VWTP still is totally broken.

@frogonwheels Michael, any idea? It seems single polls now also are throttled, which may be wrong in the first place. If they should be throttled, the API needs some method to control default throttling from JS. Throttling doesn't seem to be the VWTP issue though. Sorry this hasn't been detected earlier, I only use the ECU toolkit about once a year to check for annual service and retrieve DTCs.

The ECU toolkit's scan method is here:
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/plugin/v-vweup/ecutoolkit/xvu-ecu.js#L441

**Comment by dexterbg** [comment]
@frogonwheels Michael, the VWTP issue was caused by an incorrect change to the "done" detection in combination with resetting the `m_poll.type`. As VWTP requests consist of multiple transmissions also during the channel setup, the correct test is for `m_poll_wait` becoming zero. You first removed this test in commit a37b689b71a8b8b82186d4ca6dd6b72de41c27b6 and later added the test for the remaining frame count instead, which only applies to an actual pending response, not to channel management.

The throttling control still needs to be addressed, but isn't an issue when loading the VWUP vehicle before, as that disables the throttling, so no priority.

I found another issue with the Duktape API: `OvmsVehicle.ObdRequest()` does not return an error on request timeout. The shell command does this though:
```
OVMS# obd can1 req dev 7e0 7e8 22f191
7e0[7e8] 22f191: ERROR: timeout waiting for poller/response

OVMS# sc ev 'JSON.print(OvmsVehicle.ObdRequest({txid: 0x7e0, rxid: 0x7e8, request: "22f191"}))'
{
  "error": 0,
  "errordesc": "",
  "response": {
  },
  "response_hex": ""
}
```

This seems to be somehow caused by using the other API that was meant for simple PID reads. The shell command always uses the hex request string API, which the Duktape call previously also did. You extended that by the `type` and `pid` option, but apparently now translate all calls to that style -- maybe timeouts get lost somewhere down that chain?

**Comment by frogonwheels** [comment]
Thanks Michael

Ive been a little caught up with things. I'll try and have a think about
the throttling and follow through with the error issue.

//.ichael

**Comment by dexterbg** [comment]
The issue wasn't related to the different API methods used, in fact the outcome was pure chance. The `rx_error` variable lacked an initialization, so could have any value after a timeout, depending only on the stack situation on entry.

The other issue solved by commit 5d624c4990f06d576da97c9368fc9770143a1fdf may need some more reconsideration: as the `IncomingError()` method now also transports internal errors (negative values), using `uint16_t` for the error code isn't really correct anymore. Changing this to `int` would reflect it's now combined purpose and be cleaner than casting to `int16_t` in the single poll case.

When testing I found & fixed another issue causing crashes from erasing the poll list (passing NULL). See commit 552e4350cad92844d1bf09330db6c8685bd99390.

And I found yet another issue arising from the now asynchronous primary ticker, that might also affect ISOTP requests, see commit 614e4066b1435b729ea6038810684c5861b8f81e.

The VWTP protocol ticker assumed to be called not earlier than roughly one second after the last TX operation, so `m_poll_wait == 1` could be assumed as "1 second passed". That's no longer the case, as the now independent poller ticker primary tick can now come immediately after the TX operation.

This also means the actual waiting time from setting `m_poll_wait = 2` can now be anything from 1…2 seconds, potentially causing other issues as well. I thought about resetting the timer for a single poll, but that would interfere with a running standard poll list relying on a consistent timer interval. (Do we do that somewhere?)

The timeout hasn't been exact since we allowed multiple polls per second, but these normally were done within 50-100 ms, leaving enough headroom for the ticker to work as a timeout counter. Maybe we should raise the `m_poll_wait` resolution to ms and use a 100 ms minimum ticker interval generally? Or by default enable secondary ticks at minimum 10 per second, and extend the `m_poll_wait` decrement to the secondary runs as well?

**Comment by frogonwheels** [comment]
OH wow. This is soo good, thankyou.  (I mean bad .. but good that you've
found these).

Comments inline below:

//.ichael G


On Fri, 14 Nov 2025 at 21:30, Michael Balzer ***@***.***>
wrote:

> *dexterbg* left a comment
> (openvehicles/Open-Vehicle-Monitoring-System-3#1232)
> <https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/1232#issuecomment-3532808933>
>
> The issue wasn't related to the different API methods used, in fact the
> outcome was pure chance. The rx_error variable lacked an initialization,
> so
>
Damn, I thought I had got all the initialisations (I had checked at one
point) so I'm disappointed I missed one, thanks.

> could have any value after a timeout, depending only on the stack
> situation on entry.
>
> The other issue solved by commit 5d624c4
> <https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/commit/5d624c4990f06d576da97c9368fc9770143a1fdf>
> may need some more reconsideration: as the IncomingError() method now
> also transports internal errors (negative values), using uint16_t for the
> error code isn't really correct anymore. Changing this to int would
> reflect it's now combined purpose and be cleaner than casting to int16_t
> in the single poll case.
>
Yeah - let's not lose the sign. I can do this.  I'll pass it as an int32_t.

> When testing I found & fixed another issue causing crashes from erasing
> the poll list (passing NULL). See commit 552e435
> <https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/commit/552e4350cad92844d1bf09330db6c8685bd99390>
> .
>
  Ah.. this kind of null check is the kind of thing I'd been searching for
but just wasn't seeing... so thanks.. I'd been assuming/worried that
something like this was still happening.

> And I found yet another issue arising from the now asynchronous primary
> ticker, that might also affect ISOTP requests, see commit 614e406
> <https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/commit/614e4066b1435b729ea6038810684c5861b8f81e>
> .
>
> The VWTP protocol ticker assumed to be called not earlier than roughly one
> second after the last TX operation, so m_poll_wait == 1 could be assumed
> as "1 second passed". That's no longer the case, as the now independent
> poller ticker primary tick can now come immediately after the TX operation.
>
> This also means the actual waiting time from setting m_poll_wait = 2 can
> now be anything from 1…2 seconds, potentially causing other issues as well.
> I thought about resetting the timer for a single poll, but that would
> interfere with a running standard poll list relying on a consistent timer
> interval. (Do we do that somewhere?)
>
> The timeout hasn't been exact since we allowed multiple polls per second,
> but these normally were done within 50-100 ms, leaving enough headroom for
> the ticker to work as a timeout counter. Maybe we should raise the
> m_poll_wait resolution to ms and use a 100 ms minimum ticker interval
> generally? Or by default enable secondary ticks at minimum 10 per second,
> and extend the m_poll_wait decrement to the secondary runs as well?
>
Hmm. I like the idea of increasing the granularity of m_poll_wait.  I also
don't mind the idea of changing the subtick default.  For the ioniq 5, I
have 3 per second but only when the ECU is enabled.  There are a few ideas
in what I use then:
    PollSetTimeBetweenSuccess(80); // 80ms Gap between each successful poll.
    PollSetResponseSeparationTime(5); // Faster bursts of messages.
    PollSetTicker(300, 3); // 3 per second.
So I'm happy to consider some different defaults.  We could also make them
different based on whether the car is running.

We could hide what poll_wait is doing behind a couple of functions  bool
get_poll_waiting()  and set_poll_wait(int ms). Then we could use the clock
time.. or some other timer to gate that.  set_poll_wait( ) could just set
the current timestamp + ms and then get_poll_waiting() just sees if the
current time is >= that?

How does that seem?

**Comment by dexterbg** [comment]
Yes, something like that.

Higher ticker resolution needs to work without a car (more precisely the `NONE` car) as well, so shouldn't need or apply the vehicle state. It also shouldn't depend on `PollSetTicker()` being called, as that would add a required preparation for the use of the single request commands (shell & JS).

**Comment by frogonwheels** [comment]
Im working on the issue of the poller throttle.  Im going to add a separate
throttle for blocking polls.  Should I default to something like 10/s? Or 0
(unthrottled).


Michael

**Comment by dexterbg** [comment]
That should be unthrottled then, as throttling adds to blocking time, which is generally bad with complex queries like ECU scans. If necessary, the application using blocking requests can/shall take care for the throttling itself.

**Comment by frogonwheels** [comment]
I have some commits that I thought I'd just run live for a bit for:
* Expand error to int32_t
* Going to time-based hold.  (I've gone for 1000ms and then additional
500ms... and I'm a bit unsure of some of that without knowing what the base
requirements are.
* Defaulting to no throttling for blocking once-offs.

If you wanted to, I can push it up to my account  (and make a draft if
necessary).

//.ichael

**Comment by frogonwheels** [comment]
Michael,
I took it for a spin last night and at the least it seems stable and
functional, so I've pushed this up as a draft p/r here:
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/1262

I'd like some feedback on the timings for the time-out, and confirmation
that the once-offs are no longer throttled.

You could also play around with defaulting to a secondary timer and maybe a
poll-success separation.
    PollSetTimeBetweenSuccess(80); // 80ms Gap between each successful poll
    PollSetTicker(250, 4); //? Suggestion??

The poll success separation just uses a timer to go to the next poll,
rather than going straight to it.  This is the value I use in Ioniq 5 when
it is in 'ECU' mode.

//.ichael

**Comment by dexterbg** [comment]
I needed to change the timeouts to 2000 and remove the added get_waiting_ms() test in the VWTP module to make this work for VWTP devices.

On ISOTP devices I found a previously undetected issue: a race condition when injecting single requests (via shell or JS) while a standard polling list is active, that occasionally leads to a wrong result being returned. It looks like some partial response from a request on the standard polling list gets interpreted as the response for the single request.

The issue isn't new here but present on the `master` branch as well, but I had the (possibly unfounded) impression it happens more often with this change.

**Example**: this ISOTP read on the VW e-Up should always return error code 31 requestOutOfRange on this device (it's present on other ECUs, so needs to be tested by the scan).

```
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: Response:
04                                              | .               
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: ERROR: request failed with response error code 31 requestOutOfRange
```

```
OVMS# sc ev 'xvu.ecu.$select("C6")'
OK
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: 02c3
{
  "error": 0,
  "errordesc": "",
  "response": {
    "0": 2,
    "1": 195
  },
  "response_hex": "02c3"
}
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: 3ed5
{
  "error": 0,
  "errordesc": "",
  "response": {
    "0": 62,
    "1": 213
  },
  "response_hex": "3ed5"
}
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: 04
{
  "error": 0,
  "errordesc": "",
  "response": {
    "0": 4
  },
  "response_hex": "04"
}
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
OVMS# sc ev 'xvu.ecu.$get("220608")'
# xvu.ecu.get 220608: Request failed with response error code 31 requestOutOfRange
ERROR: Request failed with response error code 31 requestOutOfRange
```

So in case of the error, this looks like a totally valid response to the application… :-/

With the e-Up polling paused (`xvu polling pause`), the request apparently always returns the error code 31 correctly.

**Comment by frogonwheels** [comment]
Did you try increasing the timeout for the isotp?  To 1500 or 2000?
(Probably should make it a const :)).

You always got the same kind of crossed wires when running the RE Tools
when a vehicle was loaded (before the poller changes).

However, since the pollers do one call at a time per bus, then it _should_
be that the only way this could happen is if a response is delayed and the
poller times out, then sends the once-off (to the same module id) and then
the delayed response comes back, matching on the rx module id since from
what I remember we don't get the PID in the response.

Am I mistaken on this? Did I leave some loophole?

//.ichael

**Comment by dexterbg** [comment]
There are running standard polls to that ECU, yes. I'll try to catch some debug logs of what's happening, but I'll need to create a reduced polling scheme for that, as the VWUP polling list is quite complex and will flood my log channels easily.

**Comment by frogonwheels** [comment]
Did you try increasing the ISOTP wait to 2000ms?

That may be enough to fix it since the poller should serialise the calls
including the once-off polls.

//.ichael

**Comment by dexterbg** [comment]
Increasing the ISOTP timeouts to 2000 didn't help.

I now doubt that's a late response being mistaken, it rather looks like a complete fault of the response source ID filter, or maybe some race condition between switching the poll lists.

See attached shell & file log excerpts of my test session with standard VW e-Up polling running and CAN logging enabled.

The crucial faulty response with CAN logging enabled is in the shell log at `(280234)`, but according to the file log was at `(280474)` -- that was actually a period of many requests. But according to the logs, the command returning the wrong response was not resulting in a real CAN TX, but was answered immediately with:

```
OVMS# obd can1 req dev 744 7ae 220608
744[7ae] 220608: Response:
39 f5                                           | 9.              
```

The only other query running to `744` is `22 15 e2`, which also happened at that time `(280254)`, but the response contains nothing like `39 f5` as returned by the command.

The only (!) response that matches that payload in the whole session is the response to the standard poll to `7E5` with a PID read `22 1e 88`, which got answered by `7ED` exactly at the time the single request was issued:

```
2025-12-07 15:59:06.744 CET V (280464) canlog-monitor: 1765119545.784220 1T11 7E5 03 22 1e 88 55 55 55 55
2025-12-07 15:59:06.754 CET I (280474) webcommand: HttpCommandStream[0x3f8ebf70]: 3228356 bytes free, executing: obd can1 req dev 744 7ae 220608
2025-12-07 15:59:06.754 CET V (280474) canlog-monitor: 1765119545.792984 1R11 7ED 05 62 1e 88 39 f5 aa aa
```

That means the poll list response from `7ED` was mistaken as the response to the single request waiting for a response from `7AE`. That's really bad… and as mentioned before, this also happens with the current `master` poller.

[obd-singlerequest-error-test3-log.txt](https://github.com/user-attachments/files/24016625/obd-singlerequest-error-test3-log.txt)
[obd-singlerequest-error-test3-shell.txt](https://github.com/user-attachments/files/24016626/obd-singlerequest-error-test3-shell.txt)

Regards,
Michael

**Comment by frogonwheels** [comment]
I found a couple of places where the m_polls poller list was accessed
outside of the appropriate mutex.

I'm just going to run that fix on my car today and get you a p/r.

//.ichael

**Comment by frogonwheels** [comment]
Actually I decided to push to the draft p/r so you can look. Rebased to the
tip.

That includes the changes you recommended for vwtp

//.ichael

**Comment by dexterbg** [comment]
Sorry, a quick first test shows the error is still present.

**Comment by frogonwheels** [comment]
Damn..
SO, I forgot that the issue was with the vwtp protocol.  I think this bold
entry testing to make sure we are still receiving a VWTP_20 protocol
message might do it.
I think what's happened is that we've switched m_poll over to the new
message but the m_poll_vwtp is lagging behind.
All the actions on m_poll happen in the single poll task.. so I think it's
something like that.

It might also be worth zeroing m_poll_vwtp.rxid  before the ProtocolStart
is called.


bool OvmsPoller::Incoming(CAN_frame_t &frame, bool success)
  {
  // No multiframe request is active.
  if (m_poll.type == VEHICLE_POLL_TYPE_NONE)
    return false;

  // Pass frame to poller protocol handlers:
  if (*m_poll.protocol == VWTP_20* *&& *frame.origin == m_poll_vwtp.bus &&
frame.MsgID == m_poll_vwtp.rxid)

**Comment by frogonwheels** [comment]
So the 2 places I would look next are:

OvmsPoller::PollerSend
in the     case OvmsNextPollResult::FoundEntry:
where it switches the m_poll over to the new one.. it should possibly clear
out the m_poll_vwtp.rxid or something?

and then the OvmsPoller::Incoming from my last email where some extra
checking on the protocol, and then something similar to what it is doing
for the isotp protocol in filtering on the msgid against the moduleid_low
and moduleid_high range.

Again, since all of the actions on m_poll and m_poll_vwtp should absolutely
be in the poller task, it should be predictable on when things can change.

Changing the poller list _can_ be done in a different thread (and so that
other thing I found is important), but the current m_poll doesn't get
adjust until that FoundEntry case.

//.

//.ichael

**Comment by dexterbg** [comment]
> SO, I forgot that the issue was with the vwtp protocol.

No, it's with ISOTP as well. In my test case shown above there are no running VWTP polls (in fact there are none in the VW e-UP module), and the single request also is ISOTP.

**Comment by frogonwheels** [comment]
Thanks.  Found it.

I'll have a fix soon.

//.

**Comment by frogonwheels** [comment]
Ok - so I've pushed up another couple of commits to the draft p/r.

There was an issue that fits with what you were seeing.

m_iter is a pointer to the currently 'active' iterator. Generally this
would coincide with the last m_poll sent.
EXCEPT for 2 cases:

   1. When a once-off poller was inserted, it was being updated to be the
   newly inserted poller.. &
   2. When a once-off poll was deleted

Since both of these could happen from another Task, in these cases there
was a chance that the m_poll matched the incoming packet, which was then
sent off to the wrong poll series!

I believe this is what was happening.

//.ichael

**Comment by dexterbg** [comment]
That looks very good, not a single faulty response now in my test.

One new (?) issue: VWTP single requests (no polling list tested) now occasionally fail with a `timeout waiting for poller/response` error, even with standard polling paused:

```
OVMS# xvu poll pause
OBD polling status: PAUSE
OBD poller state: AWAKE
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: timeout waiting for poller/response
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: timeout waiting for poller/response
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
OVMS# obd can1 req dev -v 200 1f 22f999
200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
```

This only seems to happen with VWTP, haven't seen it with ISOTP requests.

**Comment by frogonwheels** [comment]
Hmm.
It might be worth running with  vehicle-vwtp  logging at debug to see if
anything interesting happens there?
I'm assuming you tried a longer timeout .. but default seems to be 3000
(ms) which should be plenty.

Or maybe even a shorter timeout to see if that increases the number of
timeouts we get?

Could it just be that other noise on the bus is causing the requests
/responses to be corrupt/lost somehow?

//.ichael

**Comment by dexterbg** [comment]
Attached are the shell logs of the same test executed on`mrg-fix-poller` (test4) & `master` (test5).

Timeout is the command default, I don't use different timeouts with the VW ECU plugin. Standard polling was paused so we only see the VWTP traffic -- there is no process data on the OBD bus in the VW e-Up.

Results: the timeout is also in `master` (it wasn't present when I implemented the protocol), but got much more frequent in `mrg-fix-poller`:
```
balzer@leela:~/ovms/v3> grep 22f999: obd-singlerequest-error-test4-shell.txt | sort | uniq -c
     30 200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
      5 200[1f] 22f999: ERROR: timeout waiting for poller/response
balzer@leela:~/ovms/v3> grep 22f999: obd-singlerequest-error-test5-shell.txt | sort | uniq -c
     70 200[1f] 22f999: ERROR: request failed with response error code 31 requestOutOfRange
      2 200[1f] 22f999: ERROR: timeout waiting for poller/response
```

I haven't looked into the details yet, maybe you can see something wrong right away…

[obd-singlerequest-error-test4-shell.txt](https://github.com/user-attachments/files/24149671/obd-singlerequest-error-test4-shell.txt)
[obd-singlerequest-error-test5-shell.txt](https://github.com/user-attachments/files/24149672/obd-singlerequest-error-test5-shell.txt)

**Comment by frogonwheels** [comment]
Hey Michael,

I'm really not sure what's going on. I've rebase my mrg-fix-poller branch
on the latest and added some logs in  vehicle-poll DEBUG that clarify where
the TIMEOUT error is actually coming from.

I'm expecting it to just be simply timing out on the semaphore while
waiting (Timeout Waiting on Response) .. but I would like to make sure.
If it's "No Response Allocated" then it's an avenue that is worth exploring.

Do you have any ideas on what it might be?

//.ichael

**Comment by frogonwheels** [comment]
Hi Michael, 

 

I had a closer look at obd-singlerequest-error-test4-shell.txt  and notice you had the canlog-monitor debugs there. So here’s a successful packet (or not timed-out)

D (6683154) vehicle-vwtp: [1]PollerVWTPEnter[1F]: start poll type=22 pid=F999

D (6683154) vehicle-vwtp: [1]PollerVWTPEnter[1F]: transmit frame=0 remain=0

V (6683154) canlog-monitor: 1765711935.542352 1R11 300 a1 0f 8a ff 4f ff

V (6683154) canlog-monitor: 1765711935.543534 1T11 32E 10 00 03 22 f9 99

D (6683164) vehicle-vwtp: [1]PollerVWTPEnter[1F]: receive frame=0 remain=0

V (6683164) canlog-monitor: 1765711935.553060 1R11 300 b1

D (6683194) vehicle-vwtp: PollerVWTPReceive[1F]: process OBD/UDS error 22(F999) code=31

D (6683194) vehicle-vwtp: [1]PollerVWTPEnter[1F]: idle bus=0 txid=32E rxid=300

V (6683194) canlog-monitor: 1765711935.582200 1R11 300 10 00 03 7f 22 31

V (6683194) canlog-monitor: 1765711935.582422 1T11 32E b1

V (6684204) canlog-monitor: 1765711936.592862 1R11 300 a3

 

And this is a timed out one:

 

D (6680044) vehicle-vwtp: [1]PollerVWTPEnter[1F]: start poll type=22 pid=F999

D (6680044) vehicle-vwtp: [1]PollerVWTPEnter[1F]: transmit frame=0 remain=0

V (6680064) canlog-monitor: 1765711932.446923 1T11 32E 11 00 03 22 f9 99

D (6682144) vehicle-vwtp: [1]PollerVWTPTicker[1F]: poll timeout

D (6682144) vehicle-vwtp: [1]PollerVWTPEnter[1F]: close channel bus=0 txid=32E rxid=300

V (6682144) canlog-monitor: 1765711934.526982 1T11 32E a8

 

So, I’m assuming the 1R11 frames are received and 1T11 are transmitted from the Ovms Device.

The other successful frames also had a 1R11 just before the first 1T11, which is weird? Maybe just order of logging?

 

But I guess the point is that it looks to be a genuine time-out.

Not sure what else could be going on with the canlog-monitor there??

 

//.ichael

**Comment by frogonwheels** [comment]
I’ve pushed up a change that might help.

 

It also gets rid of the check that the current poller is vwtp.  I think that’s the right move?

 

//.ichael

**Comment by dexterbg** [comment]
Sorry for the delay. I'll check & test your changes ASAP.

**Comment by dexterbg** [comment]
I've done the test now with your latest changes, and the timeout still occurs frequently:
[obd-singlerequest-error-test6-shell.txt](https://github.com/user-attachments/files/24379689/obd-singlerequest-error-test6-shell.txt)

To be sure I didn't have a false memory of the timeout not being present before the poller rework, I also did the exact same test on some commit dating back to before your first changes to the poller, I picked commit aa7762fe03158fa5b2040057a6bfc1283d7c8a9d for this test. No timeouts at all:
[obd-singlerequest-error-test7-shell.txt](https://github.com/user-attachments/files/24379690/obd-singlerequest-error-test7-shell.txt)

From a quick first comparison of the logs, I found a first substantial difference in the VWTP idle channel handling: on receiving a "ping" with an open channel (`1R11 300 a3`), the poller should respond with a "pong" (`1T11 32E a1 0f 8a ff 0a ff`). That doesn't seem to work anymore.

Regards,
Michael

**Comment by frogonwheels** [comment]
That sounds like the problem!

Ill check it out.

//.

**Comment by frogonwheels** [comment]
Ohhh, I think I might have found it.

Once the poll had succeeded, it was setting m_poll.type to
VEHICLE_POLL_NONE.  This was then cutting off further VWTP responses.

I've changed the order of responses.. and put an extra check for vwtp.state
-> Closed to avoid strange coincidences stopping stuff working.

I've rebased on top of the latest master and pushed up.

//.ichael

**Comment by dexterbg** [comment]
Yes, that looks very promising! No timeouts, and the "pongs" are present again.

Also, the ECU toolkit works flawlessly now again, even without pausing the standard poll list.

I'll test the changes in my car for a while, but I think that's it. Anything in particular, I should focus on or pay attention to?

**Comment by frogonwheels** [comment]
That's great news.
I really don't have much to add except for what you were doing.  There were
a bunch of good finds in there.

One change Im not sure about  is in vwtp where it checks timediff_ms < 200
and sets poll waiting to 2000... I took out a return from there.. let me
know if it needs to go back in.
It seems strange.. but it might be to back off before responding too
quickly.. but I really have no idea.

Michael

**Comment by dexterbg** [comment]
If the per second ticker `PollerVWTPTicker()` still gets called with a period independent of the VWTP channel setup request time, the return needs to be put back in. The check is there to prevent a false state timeout from a ticker run coming in right after the request was sent.

```
    // As a VWTP operation may start at any time between two Ticker runs,
    // we need to adjust the wait time if the ticker offset is too short:
    if (timediff_ms < 200)
      {
      set_poll_waiting(2000);
// here was the return statement
      }
    // State timeout?
…
```

If the ticker now is synchronized by `set_poll_waiting()`, i.e. comes at least a second after the request, the whole time diff check can be removed.

**Comment by dexterbg** [comment]
Originally explained here:
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/1232#issuecomment-3532808933

Btw, a side note: using snake case for the new methods breaks the API method naming convention.

**Comment by frogonwheels** [comment]
I'll fix the snake_case and make it all purty.

//.

**Comment by frogonwheels** [comment]
The draft p/r is tidied up with every commit compiling and detailing the
changes.

I've fixed up the snake_case in a couple of areas.

So the question is whether you would like this pulled into several (7?)
separate p/r or can you review it commit-by-commit and then accept the lot
in bulk?

//.ichael

**Comment by dexterbg** [comment]
I think splitting in two PRs would be good to separate the poller API change (signed error code touching specific vehicle modules) from the more internal poller blocking & timing changes & fixes.

Regarding the signed error code PR, I'd also add changing these two vehicle member variables to `int32_t` for consistency there, as these are meant to carry the error code:
```
    uint16_t            twizy_obd_rxerr;
&
    uint16_t            smarted_obd_rxerr;
```

But splitting is mostly relevant to be able to quickly revert a group of commits that turns out to be fundamentally wrong or hazardous for places/vehicles not yet tested with it. The API change isn't critical. I leave it to you to decide if you want to further split the PR, I don't think that's necessary.

**Comment by dexterbg** [comment]
We've got a new issue here: an ISO-TP `PollSingleRequest()` now fails to finish & blocks all further polling. This is fully repeatable… I'm not sure how I have missed that before.

My case: on the UpMiiGo, we use a single request to fetch the VIN when the vehicle is turned on. The request is a read request to ID 0x7E0 PID 0xF802, response coming from 0x7E8.

Attached is a debug log of that happening, with the vehicle before trickle charging the 12V battery, so polling was already running. The CAN frames indicate the request gets a valid response, the poller also processes the frames, but apparently then fails to return the result and continue with the standard polling.

[obd-singlerequest-error-test9-log.txt](https://github.com/user-attachments/files/24451207/obd-singlerequest-error-test9-log.txt)

This is critical, as it affects all vehicles using single polls.

**Comment by dexterbg** [comment]
This is the critical section:

```
2026-01-06 11:38:24.620 CET D (492080) vehicle-poll: Poll List: Added Entry !v.single (blocking)
2026-01-06 11:38:24.620 CET D (492080) events: Signal(vehicle.awake)
2026-01-06 11:38:24.620 CET D (492080) canlog-monitor: 1767695903.710571 1CEV Event vehicle.awake
2026-01-06 11:38:27.620 CET D (495080) vehicle-poll: [1]PollSingRequest: Timeout Waiting on Response
2026-01-06 11:38:27.620 CET I (495080) v-vweup: PollSetState: AWAKE -> ON
2026-01-06 11:38:27.620 CET D (495080) vehicle-poll: Pollers: Queue SetState()
2026-01-06 11:38:27.620 CET D (495080) vehicle-isotp: [1]PollerISOTPStart(Yes): send [bus=0, type=22, pid=F802], expecting 7e0/7e8-7e8
```

There is no other single request, so it seems the poller times out waiting for the request it hasn't sent yet, then sends the request.

**Comment by frogonwheels** [comment]
Right, so the core problem is that you can't call PollSingleRequest from
within the Poller Task - and PollerStateTicker is now called within the
Poller Task.

I have checked, and the vweup call is the only one that seems problematic.

It's definitely been like that for a bit, so it's not a recent regression.
 It'd be great if I could return an immediate error if it is in the poller
task.

Ioniq 5 has an example of a better way of handling the VIN request using a
non-blocking once-off poll.  I might try and implement that in the vweup if
you could check it.


//.ichael

**Comment by dexterbg** [comment]
Thanks for the quick check!

You're right, the request also fails at commit 0c5c5f6b8347758f8200d550655c537a715e20cf (before the merge) -- but it just silently fails there, leaving the VIN unset (which may well have been like that for a while, who checks the VIN…).

The new issue is, it now also blocks the polling forever. I probably missed it because I only tested the changes with charging sessions. If `PollSingleRequest()` now cannot be called from within the vehicle/poller context, that condition needs to be caught, and an error log entry needs to be added.

I'll have a look at the Ioniq 5 VIN request.

**Comment by frogonwheels** [comment]
I'm still not sure why that totally blocked.

Something like this should do it:

     // Fetch VIN once:
      if (!StdMetrics.ms_v_vin->IsDefined()) {
        auto poll_entry = std::shared_ptr<OvmsPoller::OnceOffPoll>(
            new OvmsPoller::OnceOffPoll(
              [&StdMetrics](uint16_t type, uint32_t module_sent, uint32_t
module_rec, uint16_t pid, CAN_frame_format_t format, const std::string
&data)
              {
                StdMetrics.ms_v_vin->SetValue(data.substr(1));
              }, nullptr,
              VWUP_MOT_ELEC/*txid,rxid*/, UDS_READ/*polltype*/,
VWUP_MOT_ELEC_VIN/*pid*/,
              0/*bus*/, 3/*retry*/)
            );

        PollRequest(m_can1, "!vwe.vin", poll_entry);
      }

**Comment by dexterbg** [comment]
Works → f881fad64545d7ccc894e613499fc07106fbbc17

**Comment by frogonwheels** [comment]
I'm hoping that #1319 finalises the remaining PollRequest issues uncovered.

**Comment by dexterbg** [comment]
No errors or issues on all of my tests now. Even better, especially the single requests now perform much better than with the old poller implementation: a full ECU scan on the VWUP used to take ~60 seconds, it now successfully finishes in ~40 seconds.

Thank you, Michael!
